 export const topics = [
  { id: "intro", label: "Introduction" },
  { id: "color", label: "Color Property" },
  { id: "ques1", label: "Practice Question 1" },
  { id: "colorsystem", label: "Color System" },
  { id: "ques2", label: "Practice Question 2" },
  { id: "text-align", label: "Text Property" },
  { id: "unit", label: "Units in CSS" },
  { id: "ff", label: "Font Family" },
  { id: "ques3", label: "Practice Question 3" },
  { id: "selector", label: "Selectors" },
  { id: "ques4", label: "Practice Question 4" },
  { id: "psedoclass", label: "Pseudo Class" },
  { id: "psedoelement", label: "Pseudo Element" },
  { id: "cascading", label: "Cascading CSS" },
  { id: "box", label: "Box Model" },
  { id: "ques7", label: "Practice Question 7" },
  { id: "display", label: "Display Property" },
  { id: "relative", label: "Relative Units" },
  { id: "transition", label: "Transition" },
  { id: "transform", label: "Transform" },
  { id: "box-shadow", label: "Box Shadow" },
  { id: "background-image", label: "Background Image" },
  { id: "position", label: "Position" },
  { id: "flex", label: "Flexbox" },
  { id: "grid", label: "Grid" },
  { id: "animation", label: "Animation" },
  { id: "media", label: "Media Query" },
  { id: "z-index", label: "Z Index" },
];