  export const topics = [
        { id: "intro", label: "Introduction" },
        { id: "print", label: "Hello World" },
        { id: "paragraph", label: "Paragraph" },
        { id: "headings", label: "Headings" },
        { id: "boiler", label: "Boilerplate" },
        { id: "code", label: "Boilerplate Code" },
        { id: "list", label: "Lists" },
        { id: "Attribute", label: "Attributes" },
        { id: "link", label: "Links" },
        { id: "path", label: "Paths" },
        { id: "img", label: "Images" },
        { id: "br", label: "Br Tag" },
        { id: "more", label: "Text Formatting" },
        { id: "comments", label: "Comments" },
        { id: "inline", label: "Inline vs Block" },
        { id: "div", label: "Div Element" },
        { id: "span", label: "Span Element" },
        { id: "hr", label: "Hr Tag" },
        { id: "semantic", label: "Semantic HTML" },
        { id: "table", label: "Tables" },
        { id: "form", label: "Forms" },
        { id: "Html5", label: "HTML5 Features" },
        { id: "Emmet", label: "Emmet" },
    ];